In [1]:
import os
import gzip
import shutil
import urllib.request

## Download files

In [2]:
base_url = "https://ftp.ncbi.nlm.nih.gov/geo/series/GSE131nnn/GSE131907/suppl/"

files = [
    "GSE131907_Lung_Cancer_raw_UMI_matrix.txt.gz",
]

for file in files:
    url = base_url + file
    output_path = f"../data/raw/{file}"
    

    print(f"Downloading {file}...")
    urllib.request.urlretrieve(url, output_path)

print("Download completed.")

Downloading GSE131907_Lung_Cancer_raw_UMI_matrix.txt.gz...
Download completed.

In [3]:
import scanpy as sc

adata = sc.read_text(
    "../data/raw/GSE131907_Lung_Cancer_raw_UMI_matrix.txt.gz"
).T

adata

AnnData object with n_obs × n_vars = 208506 × 29634

In [4]:
from scipy.sparse import csr_matrix
adata.X = csr_matrix(adata.X)

In [5]:
adata.write('../data/raw/GSE131907_Lung_Cancer_raw.h5ad',compression='lzf')

In [3]:
import scanpy as sc
adata =sc.read_h5ad('../data/raw/GSE131907_Lung_Cancer_raw.h5ad')

In [10]:
!pip install GEOparse

Requirement already satisfied: GEOparse in /opt/miniconda3/envs/singlecell/lib/python3.10/site-packages (2.0.4)
Requirement already satisfied: numpy>=1.7 in /opt/miniconda3/envs/singlecell/lib/python3.10/site-packages (from GEOparse) (2.2.6)
Requirement already satisfied: pandas>=0.17 in /opt/miniconda3/envs/singlecell/lib/python3.10/site-packages (from GEOparse) (2.3.3)
Requirement already satisfied: requests>=2.21.0 in /opt/miniconda3/envs/singlecell/lib/python3.10/site-packages (from GEOparse) (2.33.1)
Requirement already satisfied: tqdm>=4.31.1 in /opt/miniconda3/envs/singlecell/lib/python3.10/site-packages (from GEOparse) (4.67.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/miniconda3/envs/singlecell/lib/python3.10/site-packages (from pandas>=0.17->GEOparse) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/miniconda3/envs/singlecell/lib/python3.10/site-packages (from pandas>=0.17->GEOparse) (2026.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/miniconda3/envs/singlecell/lib/python3.10/site-packages (from pandas>=0.17->GEOparse) (2026.2)
Requirement already satisfied: six>=1.5 in /opt/miniconda3/envs/singlecell/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas>=0.17->GEOparse) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/miniconda3/envs/singlecell/lib/python3.10/site-packages (from requests>=2.21.0->GEOparse) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /opt/miniconda3/envs/singlecell/lib/python3.10/site-packages (from requests>=2.21.0->GEOparse) (3.13)
Requirement already satisfied: urllib3<3,>=1.26 in /opt/miniconda3/envs/singlecell/lib/python3.10/site-packages (from requests>=2.21.0->GEOparse) (2.6.3)
Requirement already satisfied: certifi>=2023.5.7 in /opt/miniconda3/envs/singlecell/lib/python3.10/site-packages (from requests>=2.21.0->GEOparse) (2026.4.22)

In [11]:
import GEOparse

In [12]:
obj = GEOparse.get_GEO(geo='GSE131907')
obj

11-May-2026 09:11:46 DEBUG utils - Directory ./ already exists. Skipping.
11-May-2026 09:11:46 INFO GEOparse - Downloading ftp://ftp.ncbi.nlm.nih.gov/geo/series/GSE131nnn/GSE131907/soft/GSE131907_family.soft.gz to ./GSE131907_family.soft.gz
100%|██████████| 6.92k/6.92k [00:01<00:00, 4.09kB/s]
11-May-2026 09:11:50 DEBUG downloader - Size validation passed
11-May-2026 09:11:50 DEBUG downloader - Moving /var/folders/2c/t0zd8jb93fz3r8h83rjzrppw0000gp/T/tmpphskp22w to /Users/prathiksharamesh/NSCLC-scRNAseq-Analysis/src/GSE131907_family.soft.gz
11-May-2026 09:11:50 DEBUG downloader - Successfully downloaded ftp://ftp.ncbi.nlm.nih.gov/geo/series/GSE131nnn/GSE131907/soft/GSE131907_family.soft.gz
11-May-2026 09:11:50 INFO GEOparse - Parsing ./GSE131907_family.soft.gz:
11-May-2026 09:11:50 DEBUG GEOparse - DATABASE: GeoMiame
11-May-2026 09:11:50 DEBUG GEOparse - SERIES: GSE131907
11-May-2026 09:11:50 DEBUG GEOparse - PLATFORM: GPL16791
11-May-2026 09:11:50 DEBUG GEOparse - SAMPLE: GSM3827114
11-May-2026 09:11:50 DEBUG GEOparse - SAMPLE: GSM3827115
11-May-2026 09:11:50 DEBUG GEOparse - SAMPLE: GSM3827116
11-May-2026 09:11:50 DEBUG GEOparse - SAMPLE: GSM3827117
11-May-2026 09:11:50 DEBUG GEOparse - SAMPLE: GSM3827118
11-May-2026 09:11:50 DEBUG GEOparse - SAMPLE: GSM3827119
11-May-2026 09:11:50 DEBUG GEOparse - SAMPLE: GSM3827120
11-May-2026 09:11:50 DEBUG GEOparse - SAMPLE: GSM3827121
11-May-2026 09:11:50 DEBUG GEOparse - SAMPLE: GSM3827122
11-May-2026 09:11:50 DEBUG GEOparse - SAMPLE: GSM3827123
11-May-2026 09:11:50 DEBUG GEOparse - SAMPLE: GSM3827124
11-May-2026 09:11:50 DEBUG GEOparse - SAMPLE: GSM3827125
11-May-2026 09:11:50 DEBUG GEOparse - SAMPLE: GSM3827126
11-May-2026 09:11:50 DEBUG GEOparse - SAMPLE: GSM3827127
11-May-2026 09:11:50 DEBUG GEOparse - SAMPLE: GSM3827128
11-May-2026 09:11:50 DEBUG GEOparse - SAMPLE: GSM3827129
11-May-2026 09:11:50 DEBUG GEOparse - SAMPLE: GSM3827130
11-May-2026 09:11:50 DEBUG GEOparse - SAMPLE: GSM3827131
11-May-2026 09:11:50 DEBUG GEOparse - SAMPLE: GSM3827132
11-May-2026 09:11:50 DEBUG GEOparse - SAMPLE: GSM3827133
11-May-2026 09:11:50 DEBUG GEOparse - SAMPLE: GSM3827134
11-May-2026 09:11:50 DEBUG GEOparse - SAMPLE: GSM3827135
11-May-2026 09:11:50 DEBUG GEOparse - SAMPLE: GSM3827136
11-May-2026 09:11:50 DEBUG GEOparse - SAMPLE: GSM3827137
11-May-2026 09:11:50 DEBUG GEOparse - SAMPLE: GSM3827138
11-May-2026 09:11:50 DEBUG GEOparse - SAMPLE: GSM3827139
11-May-2026 09:11:50 DEBUG GEOparse - SAMPLE: GSM3827140
11-May-2026 09:11:50 DEBUG GEOparse - SAMPLE: GSM3827141
11-May-2026 09:11:50 DEBUG GEOparse - SAMPLE: GSM3827142
11-May-2026 09:11:50 DEBUG GEOparse - SAMPLE: GSM3827143
11-May-2026 09:11:50 DEBUG GEOparse - SAMPLE: GSM3827144
11-May-2026 09:11:50 DEBUG GEOparse - SAMPLE: GSM3827145
11-May-2026 09:11:50 DEBUG GEOparse - SAMPLE: GSM3827146
11-May-2026 09:11:50 DEBUG GEOparse - SAMPLE: GSM3827147
11-May-2026 09:11:51 DEBUG GEOparse - SAMPLE: GSM3827148
11-May-2026 09:11:51 DEBUG GEOparse - SAMPLE: GSM3827149
11-May-2026 09:11:51 DEBUG GEOparse - SAMPLE: GSM3827150
11-May-2026 09:11:51 DEBUG GEOparse - SAMPLE: GSM3827151
11-May-2026 09:11:51 DEBUG GEOparse - SAMPLE: GSM3827152
11-May-2026 09:11:51 DEBUG GEOparse - SAMPLE: GSM3827153
11-May-2026 09:11:51 DEBUG GEOparse - SAMPLE: GSM3827154
11-May-2026 09:11:51 DEBUG GEOparse - SAMPLE: GSM3827155
11-May-2026 09:11:51 DEBUG GEOparse - SAMPLE: GSM3827156
11-May-2026 09:11:51 DEBUG GEOparse - SAMPLE: GSM3827157
11-May-2026 09:11:51 DEBUG GEOparse - SAMPLE: GSM3827158
11-May-2026 09:11:51 DEBUG GEOparse - SAMPLE: GSM3827159
11-May-2026 09:11:51 DEBUG GEOparse - SAMPLE: GSM3827160
11-May-2026 09:11:51 DEBUG GEOparse - SAMPLE: GSM3827161
11-May-2026 09:11:51 DEBUG GEOparse - SAMPLE: GSM3827162
11-May-2026 09:11:51 DEBUG GEOparse - SAMPLE: GSM3827163
11-May-2026 09:11:51 DEBUG GEOparse - SAMPLE: GSM3827164
11-May-2026 09:11:51 DEBUG GEOparse - SAMPLE: GSM3827165
11-May-2026 09:11:51 DEBUG GEOparse - SAMPLE: GSM3827166
11-May-2026 09:11:51 DEBUG GEOparse - SAMPLE: GSM3827167
11-May-2026 09:11:51 DEBUG GEOparse - SAMPLE: GSM3827168
11-May-2026 09:11:51 DEBUG GEOparse - SAMPLE: GSM3827169
11-May-2026 09:11:51 DEBUG GEOparse - SAMPLE: GSM3827170
11-May-2026 09:11:51 DEBUG GEOparse - SAMPLE: GSM3827171

In [13]:
meta = obj.phenotype_data
meta.head()

,title,geo_accession,status,submission_date,last_update_date,type,channel_count,source_name_ch1,organism_ch1,taxid_ch1,...,contact_zip/postal_code,contact_country,instrument_model,library_selection,library_source,library_strategy,relation,supplementary_file_1,series_id,data_row_count
GSM3827114,LUNG_N01,GSM3827114,Public on Mar 27 2020,May 29 2019,Aug 02 2022,SRA,1,Normal lung,Homo sapiens,9606,...,06591,South Korea,Illumina HiSeq 2500,cDNA,transcriptomic,RNA-Seq,"Reanalyzed by: GSE210347,BioSample: https://ww...",NONE,GSE131907,0
GSM3827115,LUNG_N06,GSM3827115,Public on Mar 27 2020,May 29 2019,Aug 02 2022,SRA,1,Normal lung,Homo sapiens,9606,...,06591,South Korea,Illumina HiSeq 2500,cDNA,transcriptomic,RNA-Seq,"Reanalyzed by: GSE210347,BioSample: https://ww...",NONE,GSE131907,0
GSM3827116,LUNG_N08,GSM3827116,Public on Mar 27 2020,May 29 2019,Aug 02 2022,SRA,1,Normal lung,Homo sapiens,9606,...,06591,South Korea,Illumina HiSeq 2500,cDNA,transcriptomic,RNA-Seq,"Reanalyzed by: GSE210347,BioSample: https://ww...",NONE,GSE131907,0
GSM3827117,LUNG_N09,GSM3827117,Public on Mar 27 2020,May 29 2019,Aug 02 2022,SRA,1,Normal lung,Homo sapiens,9606,...,06591,South Korea,Illumina HiSeq 2500,cDNA,transcriptomic,RNA-Seq,"Reanalyzed by: GSE210347,BioSample: https://ww...",NONE,GSE131907,0
GSM3827118,LUNG_N18,GSM3827118,Public on Mar 27 2020,May 29 2019,Aug 02 2022,SRA,1,Normal lung,Homo sapiens,9606,...,06591,South Korea,Illumina HiSeq 2500,cDNA,transcriptomic,RNA-Seq,"Reanalyzed by: GSE210347,BioSample: https://ww...",NONE,GSE131907,0

In [16]:
meta['title'].value_counts

<bound method IndexOpsMixin.value_counts of GSM3827114       LUNG_N01
GSM3827115       LUNG_N06
GSM3827116       LUNG_N08
GSM3827117       LUNG_N09
GSM3827118       LUNG_N18
GSM3827119       LUNG_N19
GSM3827120       LUNG_N20
GSM3827121       LUNG_N28
GSM3827122       LUNG_N30
GSM3827123       LUNG_N31
GSM3827124       LUNG_N34
GSM3827125       LUNG_T06
GSM3827126       LUNG_T08
GSM3827127       LUNG_T09
GSM3827128       LUNG_T18
GSM3827129       LUNG_T19
GSM3827130       LUNG_T20
GSM3827131       LUNG_T25
GSM3827132       LUNG_T28
GSM3827133       LUNG_T30
GSM3827134       LUNG_T31
GSM3827135       LUNG_T34
GSM3827136        EBUS_06
GSM3827137        EBUS_28
GSM3827138        EBUS_49
GSM3827139     BRONCHO_58
GSM3827140        EBUS_10
GSM3827141     BRONCHO_11
GSM3827142        EBUS_12
GSM3827143        EBUS_13
GSM3827144        EBUS_15
GSM3827145        EBUS_19
GSM3827146        EBUS_51
GSM3827147          LN_01
GSM3827148          LN_02
GSM3827149          LN_03
GSM3827150          LN_04
GSM3827151          LN_05
GSM3827152          LN_06
GSM3827153          LN_07
GSM3827154          LN_08
GSM3827155          LN_11
GSM3827156          LN_12
GSM3827157    EFFUSION_06
GSM3827158    EFFUSION_11
GSM3827159    EFFUSION_12
GSM3827160    EFFUSION_13
GSM3827161    EFFUSION_64
GSM3827162          NS_02
GSM3827163          NS_03
GSM3827164          NS_04
GSM3827165          NS_06
GSM3827166          NS_07
GSM3827167          NS_12
GSM3827168          NS_13
GSM3827169          NS_16
GSM3827170          NS_17
GSM3827171          NS_19
Name: title, dtype: object>

In [18]:
adata.obs

Empty DataFrame
Columns: []
Index: [AAACCTGAGAAACCGC_LN_05, AAACCTGAGAAACGCC_NS_13, AAACCTGAGAAGGTGA_LUNG_N18, AAACCTGAGACAAAGG_LUNG_N18, AAACCTGAGACATAAC_LN_04, AAACCTGAGACCTTTG_LUNG_N30, AAACCTGAGACGACGT_LUNG_T09, AAACCTGAGACGACGT_LUNG_T34, AAACCTGAGACGCTTT_LUNG_T18, AAACCTGAGACGCTTT_NS_04, AAACCTGAGACTGGGT_LUNG_N30, AAACCTGAGACTGTAA_LUNG_T34, AAACCTGAGAGCAATT_EFFUSION_06, AAACCTGAGAGCAATT_LUNG_N31, AAACCTGAGAGCCTAG_LUNG_N20, AAACCTGAGAGGGATA_LUNG_N08, AAACCTGAGAGGGATA_NS_19, AAACCTGAGAGGTTGC_BRONCHO_11, AAACCTGAGAGTGACC_BRONCHO_58, AAACCTGAGAGTGACC_EFFUSION_06, AAACCTGAGATATGCA_LUNG_T25, AAACCTGAGATGGGTC_EFFUSION_12, AAACCTGAGATGTCGG_LUNG_T31, AAACCTGAGATGTGGC_LUNG_N06, AAACCTGAGATGTGTA_NS_17, AAACCTGAGCAATATG_LUNG_N34, AAACCTGAGCACCGCT_LUNG_N08, AAACCTGAGCACGCCT_LUNG_N18, AAACCTGAGCAGACTG_NS_02, AAACCTGAGCAGGTCA_LN_12, AAACCTGAGCCAGGAT_EBUS_28, AAACCTGAGCCCAACC_EFFUSION_64, AAACCTGAGCCTATGT_LUNG_T28, AAACCTGAGCCTCGTG_NS_16, AAACCTGAGCGACGTA_LUNG_T06, AAACCTGAGCGATAGC_LN_07, AAACCTGAGCGCTTAT_LUNG_T19, AAACCTGAGCGGATCA_NS_17, AAACCTGAGCGTTCCG_NS_16, AAACCTGAGCTAAACA_LUNG_T34, AAACCTGAGCTACCTA_LUNG_T34, AAACCTGAGCTAGCCC_EFFUSION_06, AAACCTGAGCTAGGCA_EBUS_28, AAACCTGAGCTAGTCT_EFFUSION_12, AAACCTGAGCTGAAAT_LUNG_N34, AAACCTGAGCTGGAAC_NS_04, AAACCTGAGGAATTAC_LUNG_T30, AAACCTGAGGAGCGTT_EBUS_10, AAACCTGAGGAGCGTT_NS_02, AAACCTGAGGAGTACC_EBUS_10, AAACCTGAGGAGTTTA_LUNG_T30, AAACCTGAGGATCGCA_LUNG_T28, AAACCTGAGGATGGAA_LUNG_T31, AAACCTGAGGCAAAGA_LUNG_T06, AAACCTGAGGCAATTA_LUNG_N09, AAACCTGAGGCCCTTG_EBUS_49, AAACCTGAGGCGACAT_LUNG_T18, AAACCTGAGGCTACGA_LN_03, AAACCTGAGGCTATCT_EFFUSION_06, AAACCTGAGGGCTTGA_NS_07, AAACCTGAGGGTGTGT_LUNG_N08, AAACCTGAGGGTTCCC_LUNG_N20, AAACCTGAGGGTTTCT_EFFUSION_64, AAACCTGAGGTAAACT_EBUS_49, AAACCTGAGGTAAACT_LUNG_T30, AAACCTGAGGTACTCT_EFFUSION_06, AAACCTGAGGTGCTAG_LN_06, AAACCTGAGGTGCTTT_EBUS_19, AAACCTGAGTAATCCC_LUNG_N34, AAACCTGAGTAGGTGC_LUNG_N31, AAACCTGAGTATCGAA_LUNG_N18, AAACCTGAGTATTGGA_LN_08, AAACCTGAGTCAAGCG_LN_12, AAACCTGAGTCATCCA_LUNG_T08, AAACCTGAGTCCAGGA_LUNG_T20, AAACCTGAGTCCGTAT_LN_07, AAACCTGAGTCCTCCT_EBUS_51, AAACCTGAGTCGATAA_LUNG_T09, AAACCTGAGTCGCCGT_LUNG_N30, AAACCTGAGTCTCAAC_LUNG_N19, AAACCTGAGTCTTGCA_BRONCHO_58, AAACCTGAGTGAAGTT_LUNG_N06, AAACCTGAGTGAATTG_NS_19, AAACCTGAGTGACATA_LUNG_T09, AAACCTGAGTGACTCT_EBUS_10, AAACCTGAGTGCGATG_EBUS_10, AAACCTGAGTGCGATG_NS_17, AAACCTGAGTGCGTGA_LUNG_N18, AAACCTGAGTGGACGT_LUNG_N31, AAACCTGAGTGGAGAA_EBUS_10, AAACCTGAGTGTGAAT_LN_03, AAACCTGAGTGTGAAT_LUNG_N18, AAACCTGAGTGTGGCA_LUNG_T20, AAACCTGAGTGTTGAA_LUNG_T06, AAACCTGAGTTAGGTA_NS_13, AAACCTGAGTTGCAGG_LUNG_N18, AAACCTGAGTTGCAGG_LUNG_T06, AAACCTGAGTTGTCGT_LUNG_N01, AAACCTGCAAACGCGA_LUNG_N34, AAACCTGCAAACGTGG_LUNG_N20, ...]

[208506 rows x 0 columns]

In [20]:
adata.obs["title"] = adata.obs.index.str.replace(r"^[^_]+_", "", regex=True)

# view
adata.obs[["title"]].head()

                              title
AAACCTGAGAAACCGC_LN_05        LN_05
AAACCTGAGAAACGCC_NS_13        NS_13
AAACCTGAGAAGGTGA_LUNG_N18  LUNG_N18
AAACCTGAGACAAAGG_LUNG_N18  LUNG_N18
AAACCTGAGACATAAC_LN_04        LN_04

In [21]:
adata.obs

                                    title
AAACCTGAGAAACCGC_LN_05              LN_05
AAACCTGAGAAACGCC_NS_13              NS_13
AAACCTGAGAAGGTGA_LUNG_N18        LUNG_N18
AAACCTGAGACAAAGG_LUNG_N18        LUNG_N18
AAACCTGAGACATAAC_LN_04              LN_04
...                                   ...
TTTGTCATCTTGCCGT_LUNG_T30        LUNG_T30
TTTGTCATCTTGTATC_EFFUSION_13  EFFUSION_13
TTTGTCATCTTTACAC_LUNG_N20        LUNG_N20
TTTGTCATCTTTACAC_LUNG_T25        LUNG_T25
TTTGTCATCTTTAGGG_LUNG_T31        LUNG_T31

[208506 rows x 1 columns]

In [22]:
meta.rename(columns={'geo_accession':'sample'}, inplace=True)

In [23]:
adata.obs = adata.obs.reset_index().merge(meta, how='left', on='title')
adata.obs

,index,title,sample,status,submission_date,last_update_date,type,channel_count,source_name_ch1,organism_ch1,...,contact_zip/postal_code,contact_country,instrument_model,library_selection,library_source,library_strategy,relation,supplementary_file_1,series_id,data_row_count
0,AAACCTGAGAAACCGC_LN_05,LN_05,GSM3827151,Public on Mar 27 2020,May 29 2019,Aug 18 2021,SRA,1,Normal lymph node,Homo sapiens,...,06591,South Korea,Illumina HiSeq 2500,cDNA,transcriptomic,RNA-Seq,BioSample: https://www.ncbi.nlm.nih.gov/biosam...,NONE,GSE131907,0
1,AAACCTGAGAAACGCC_NS_13,NS_13,GSM3827168,Public on Mar 27 2020,May 29 2019,Aug 18 2021,SRA,1,Metastatic brain,Homo sapiens,...,06591,South Korea,Illumina HiSeq 2500,cDNA,transcriptomic,RNA-Seq,BioSample: https://www.ncbi.nlm.nih.gov/biosam...,NONE,GSE131907,0
2,AAACCTGAGAAGGTGA_LUNG_N18,LUNG_N18,GSM3827118,Public on Mar 27 2020,May 29 2019,Aug 02 2022,SRA,1,Normal lung,Homo sapiens,...,06591,South Korea,Illumina HiSeq 2500,cDNA,transcriptomic,RNA-Seq,"Reanalyzed by: GSE210347,BioSample: https://ww...",NONE,GSE131907,0
3,AAACCTGAGACAAAGG_LUNG_N18,LUNG_N18,GSM3827118,Public on Mar 27 2020,May 29 2019,Aug 02 2022,SRA,1,Normal lung,Homo sapiens,...,06591,South Korea,Illumina HiSeq 2500,cDNA,transcriptomic,RNA-Seq,"Reanalyzed by: GSE210347,BioSample: https://ww...",NONE,GSE131907,0
4,AAACCTGAGACATAAC_LN_04,LN_04,GSM3827150,Public on Mar 27 2020,May 29 2019,Aug 18 2021,SRA,1,Normal lymph node,Homo sapiens,...,06591,South Korea,Illumina HiSeq 2500,cDNA,transcriptomic,RNA-Seq,BioSample: https://www.ncbi.nlm.nih.gov/biosam...,NONE,GSE131907,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
208501,TTTGTCATCTTGCCGT_LUNG_T30,LUNG_T30,GSM3827133,Public on Mar 27 2020,May 29 2019,Aug 02 2022,SRA,1,Tumour lung,Homo sapiens,...,06591,South Korea,Illumina HiSeq 2500,cDNA,transcriptomic,RNA-Seq,"Reanalyzed by: GSE210347,BioSample: https://ww...",NONE,GSE131907,0
208502,TTTGTCATCTTGTATC_EFFUSION_13,EFFUSION_13,GSM3827160,Public on Mar 27 2020,May 29 2019,Aug 18 2021,SRA,1,Pleural effusion,Homo sapiens,...,06591,South Korea,Illumina HiSeq 2500,cDNA,transcriptomic,RNA-Seq,BioSample: https://www.ncbi.nlm.nih.gov/biosam...,NONE,GSE131907,0
208503,TTTGTCATCTTTACAC_LUNG_N20,LUNG_N20,GSM3827120,Public on Mar 27 2020,May 29 2019,Aug 02 2022,SRA,1,Normal lung,Homo sapiens,...,06591,South Korea,Illumina HiSeq 2500,cDNA,transcriptomic,RNA-Seq,"Reanalyzed by: GSE210347,BioSample: https://ww...",NONE,GSE131907,0
208504,TTTGTCATCTTTACAC_LUNG_T25,LUNG_T25,GSM3827131,Public on Mar 27 2020,May 29 2019,Aug 02 2022,SRA,1,Tumour lung,Homo sapiens,...,06591,South Korea,Illumina HiSeq 2500,cDNA,transcriptomic,RNA-Seq,"Reanalyzed by: GSE210347,BioSample: https://ww...",NONE,GSE131907,0
208505,TTTGTCATCTTTAGGG_LUNG_T31,LUNG_T31,GSM3827134,Public on Mar 27 2020,May 29 2019,Aug 02 2022,SRA,1,Tumour lung,Homo sapiens,...,06591,South Korea,Illumina HiSeq 2500,cDNA,transcriptomic,RNA-Seq,"Reanalyzed by: GSE210347,BioSample: https://ww...",NONE,GSE131907,0

In [25]:
adata.obs.isna().sum()

index                                              0
title                                              0
sample                                             0
status                                             0
submission_date                                    0
last_update_date                                   0
type                                               0
channel_count                                      0
source_name_ch1                                    0
organism_ch1                                       0
taxid_ch1                                          0
characteristics_ch1.0.patient id                   0
characteristics_ch1.1.tumor stage                  0
characteristics_ch1.2.tissue origin abbrevation    0
characteristics_ch1.3.lung cancer subtype          0
growth_protocol_ch1                                0
molecule_ch1                                       0
extract_protocol_ch1                               0
description                                        0
data_processing                                    0
platform_id                                        0
contact_name                                       0
contact_email                                      0
contact_phone                                      0
contact_department                                 0
contact_institute                                  0
contact_address                                    0
contact_city                                       0
contact_zip/postal_code                            0
contact_country                                    0
instrument_model                                   0
library_selection                                  0
library_source                                     0
library_strategy                                   0
relation                                           0
supplementary_file_1                               0
series_id                                          0
data_row_count                                     0
dtype: int64

In [26]:
adata.write('../data/raw/GSE131907_Lung_Cancer_raw_with_metadata.h5ad',compression='lzf')